package soap_server_backup;


/**
* soap_server_backup/IControllerCopySecurityPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IServerBackup.idl
* Monday, August 8, 2022 10:20:54 AM COT
*/

public abstract class IControllerCopySecurityPOA extends org.omg.PortableServer.Servant
 implements soap_server_backup.IControllerCopySecurityOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("saveCopySong", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // soap_server_backup/IControllerCopySecurity/saveCopySong
       {
         soap_server_backup.IControllerCopySecurityPackage.SongDTO objSong = soap_server_backup.IControllerCopySecurityPackage.SongDTOHelper.read (in);
         boolean $result = false;
         $result = this.saveCopySong (objSong);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:soap_server_backup/IControllerCopySecurity:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public IControllerCopySecurity _this() 
  {
    return IControllerCopySecurityHelper.narrow(
    super._this_object());
  }

  public IControllerCopySecurity _this(org.omg.CORBA.ORB orb) 
  {
    return IControllerCopySecurityHelper.narrow(
    super._this_object(orb));
  }


} // class IControllerCopySecurityPOA
