package soap_server_backup.IControllerCopySecurityPackage;


/**
* soap_server_backup/IControllerCopySecurityPackage/SongDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IServerBackup.idl
* Monday, August 8, 2022 10:20:54 AM COT
*/

public final class SongDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String artist = null;
  public String title = null;
  public String type = null;
  public int sizeMB = (int)0;
  public byte arrayBytes[] = null;

  public SongDTO ()
  {
  } // ctor

  public SongDTO (int _id, String _artist, String _title, String _type, int _sizeMB, byte[] _arrayBytes)
  {
    id = _id;
    artist = _artist;
    title = _title;
    type = _type;
    sizeMB = _sizeMB;
    arrayBytes = _arrayBytes;
  } // ctor

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getArtist() {
        return artist;
    }

    public void setArtist(String artist) {
        this.artist = artist;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public int getSizeMB() {
        return sizeMB;
    }

    public void setSizeMB(int sizeMB) {
        this.sizeMB = sizeMB;
    }

    public byte[] getArrayBytes() {
        return arrayBytes;
    }

    public void setArrayBytes(byte[] arrayBytes) {
        this.arrayBytes = arrayBytes;
    }
    
} // class SongDTO
