package soap_server_backup.IControllerCopySecurityPackage;

/**
* soap_server_backup/IControllerCopySecurityPackage/SongDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IServerBackup.idl
* Monday, August 8, 2022 10:20:54 AM COT
*/

public final class SongDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public soap_server_backup.IControllerCopySecurityPackage.SongDTO value = null;

  public SongDTOHolder ()
  {
  }

  public SongDTOHolder (soap_server_backup.IControllerCopySecurityPackage.SongDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = soap_server_backup.IControllerCopySecurityPackage.SongDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    soap_server_backup.IControllerCopySecurityPackage.SongDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return soap_server_backup.IControllerCopySecurityPackage.SongDTOHelper.type ();
  }

}
