package soap_server_backup.IControllerCopySecurityPackage;


/**
* soap_server_backup/IControllerCopySecurityPackage/streamBytesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IServerBackup.idl
* Monday, August 8, 2022 10:20:54 AM COT
*/

public final class streamBytesHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[] = null;

  public streamBytesHolder ()
  {
  }

  public streamBytesHolder (byte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = soap_server_backup.IControllerCopySecurityPackage.streamBytesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    soap_server_backup.IControllerCopySecurityPackage.streamBytesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return soap_server_backup.IControllerCopySecurityPackage.streamBytesHelper.type ();
  }

}
