package soap_server_backup;


/**
* soap_server_backup/IControllerCopySecurityOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IServerBackup.idl
* Monday, August 8, 2022 10:20:54 AM COT
*/

public interface IControllerCopySecurityOperations 
{
  boolean saveCopySong (soap_server_backup.IControllerCopySecurityPackage.SongDTO objSong);
} // interface IControllerCopySecurityOperations
