package soap_server_backup;

/**
* soap_server_backup/IControllerCopySecurityHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IServerBackup.idl
* Monday, August 8, 2022 10:20:54 AM COT
*/

public final class IControllerCopySecurityHolder implements org.omg.CORBA.portable.Streamable
{
  public soap_server_backup.IControllerCopySecurity value = null;

  public IControllerCopySecurityHolder ()
  {
  }

  public IControllerCopySecurityHolder (soap_server_backup.IControllerCopySecurity initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = soap_server_backup.IControllerCopySecurityHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    soap_server_backup.IControllerCopySecurityHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return soap_server_backup.IControllerCopySecurityHelper.type ();
  }

}
